FROM python:3.11.4-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

RUN chmod +x /app/sandbox/api/run_server.sh
EXPOSE 8000

ENTRYPOINT ["sh", "/app/sandbox/api/run_server.sh"]
CMD ["tail", "-f", "/dev/null"]
